# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6gspHLkDaPplwNoKhmaFpiL1hOqj2nt
"""

#bibliotecas
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

#carregar imagem
img = Image.open('/content/sung-jinwoo-dagger-solo-leveling-arise-hd-wallpaper-uhdpaper.com-168@5@d.jpg')

#Mostra a imagem
plt.imshow(img)