# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFqem6BMln1eJ5R9TaZSF67zkfZ_Ftjk

Aula prática 01: Transformando uma imagem no seu negativo(cores invertidas)
"""

import cv2
import  numpy as np
import matplotlib.pyplot as plt

# carregar uma imagem (insira o caminho da imagem)
imagem_rgb = cv2.imread('/content/1362_3ffc1.jpg')

#imagem de BGR (padrão openCV) para RGB
imagem_rgb = cv2.cvtColor(imagem_rgb, cv2.COLOR_BGR2RGB)

#Inverte os canais de cor (para negativo)
imagem_negativa = 255 - imagem_rgb

#Exibir as imagens
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(imagem_rgb)
plt.title('Original')
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(imagem_negativa)
plt.title('Negativo')
plt.axis('off')

plt.show()