# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6gspHLkDaPplwNoKhmaFpiL1hOqj2nt
"""

#bibliotecas
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

#carregar imagem
img = Image.open('/content/sung-jinwoo-dagger-solo-leveling-arise-hd-wallpaper-uhdpaper.com-168@5@d.jpg')

#Mostra a imagem
plt.imshow(img)

#converte para a escala de cinza
imagem_cinza = img.convert('L')

#Mostra a imagem em escala de cinza
plt.imshow(imagem_cinza, cmap='gray')

# Obter largura e altura da imagem (em px)
largura, altura = imagem_cinza.size

print(f'Largura: {largura} px')
print(f'Altura: {altura} px')

# definir nova largura e altura da imagem
valor = 50
nova_largura = int(largura/valor)
nova_altura = int(altura/valor)

print(nova_largura)
print(nova_altura)

#redimensionar a imagem
imagem_redimensionada = imagem_cinza.resize((nova_largura, nova_altura))

#mostra a imagem
plt.imshow(imagem_redimensionada, cmap='gray')